version = 0.1
[default.deploy.parameters]
stack_name = "teste-lets"
resolve_s3 = true
s3_prefix = "teste-lets"
region = "sa-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
