# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  teste-lets

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  listClientsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: clients/list-handler.handler
      CodeUri: dist/src
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Lists the clients on the api
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Ref clientsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /clients/
            Method: GET
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: get-by-id.js
  getClientByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: clients/get-handler.handler
      CodeUri: dist/src
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Get a client by its id
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Ref clientsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /clients/{id}
            Method: GET
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: create-handler.js
  addClientFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: clients/create-handler.handler
      CodeUri: dist/src
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Creates a new client
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Ref clientsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /clients/
            Method: POST
  
  updateClientByIdFunciton:
    Type: AWS::Serverless::Function
    Properties:
      Handler: clients/update-handler.handler
      Runtime: nodejs22.x
      CodeUri: dist/src
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Updates a client by it's id
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Ref clientsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /clients/{id}
            Method: PATCH

  deleteClientByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: clients/delete-handler.handler
      CodeUri: dist/src
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Deletes a client by it's id 
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Ref clientsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /clients/{id}
            Method: DELETE 

  # Simple syntax to create a DynamoDB table with a single attribute primary key, more in
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlesssimpletable

  # DynamoDB table to store item: {id: &lt;ID&gt;, name: &lt;NAME&gt;}
  clientsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 'clients'
      AttributeDefinitions:
        - AttributeName: 'clientId'
          AttributeType: S
      KeySchema:
        - AttributeName: 'clientId'
          KeyType: HASH
       
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1 

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
